- MissionAlertBot.py
Type check the input value.
Fixes: #53
> eng/PR-53 Findid should throw an error if value is not an int

- MissionAlertBot.py
- constants.py
- tests/test_constants.py
Add a test upvote channel
Fixed: #54
> eng/PR-54 Testing mode needs upvotes channel

- MissionAlertBot.py
Use underscores to the name
Fixes: #59
> eng/PR-59 Env var should use underscore not hyphen

- MissionAlertBot.py
> Station pad size should follow Station name in all cases, m.ission command text reorder

- MissionAlertBot.py
Unclear why but now the ints are no longer being passed in, they are strings. Just convert it again.
> eng/PR-65 FindID is broken

- MissionAlertBot.py
> eng/PR-63  Fix production bot token value

- MissionAlertBot.py
> Merge dev to main

- MissionAlertBot.py
Reduce the carrier_list length
Fixes: #68
> eng/PR-68 Reduce the carrier_list embed length

- MissionAlertBot.py
Reddit title should not use posix time
Fixes: #70
> eng/PR-70  Fixed reddit date formatting

- MissionAlertBot.py
- constants.py
- requirements.txt
> Implement carrier crew signups using /crew slash command

- CarrierData.py
- MissionAlertBot.py
Closes #87 , preparation for #89, #90 and #93
> Add carrier owner's Discord user ID to carrier database

- MissionAlertBot.py
- constants.py
Fixes #17 #52 #101
Also changed ID of trade_alerts on test server to new channel
> Update Discord carrier channel "mission starting" embed

- MissionAlertBot.py
- requirements.txt
Requires Discord.py version 1.7 or higher
Fixes #93
> Set channel permissions for owner during m.carrier_add

- MissionAlertBot.py
> Discord trade alert shows supply instead of demand when unloading

- MissionAlertBot.py
> Fix crew role mention

- MissionAlertBot.py
Completes #19  #119 
Also shortens mission generator feedback for less channel scroll
(Note that @ mentions in embeds do not generate pings)
> Streamline mgen feedback, ping owners, update find

- MissionAlertBot.py
Resolves #88 
Beginning of framework towards #121
> Implement crew role pings on mission generation

- MissionAlertBot.py
> carrier_edit should rename shortname.png if shortname is edited

- MissionAlertBot.py
Added new command /crews
Fixes #112
> Add a slash command to tell a user what crews they are on

- MissionAlertBot.py
Add the timestamp and timezone to Reddit mission creation
Fixes: #99
> Reddit text no longer includes time of mission creation

- MissionAlertBot.py
Find short should return multiple matches
> Find carrier should return all the carriers, not just the first match

- MissionAlertBot.py
> Clean up (delete) embed/response pairs after each segment of m.carrier_edit

- MissionAlertBot.py
> Add a command to list the number of people signed to each carrier role

- MissionAlertBot.py
> Corrected typo

- MissionAlertBot.py
> check_confirm shouldn't be async

- MissionAlertBot.py
> Write roleid and ownerid to db with carrier_edit

- MissionAlertBot.py
Write to a temp file instead.
Fixes #152
> Generating multiple missions at once can pollute result.png

- MissionAlertBot.py
> Clarify m.carrier_image instructions

- MissionAlertBot.py
Closes #118 
New private slash commands:
`/mission`
`/missions`
`/info`
`/find <carriername>`
`/owner @owner`
> Add new utility slash commands

- MissionAlertBot.py
Skip posting for low profit trades.  Fixes #170
> Disallow posting of sub-10k trades to Reddit

- CarrierData.py
- MissionAlertBot.py
- constants.py
> Replace Crew roles with single Hauler role

- CommunityCarrierData.py
- MissionAlertBot.py
- constants.py
> Added community carrier commands

- MissionAlertBot.py
Check for float not int
Fixes #176
> Posting a float instead of an int causes posting to fail

- MissionAlertBot.py
> Unresolved ref to mission_temp_channel_id

- MissionAlertBot.py
> Print carrier owners in carrier_list command

- MissionAlertBot.py
> important updates

- MissionAlertBot.py
- constants.py
> DM reddit replies to Carrier Owner

- MissionAlertBot.py
- NomineesData.py
- constants.py
> Added nominee commands

- MissionAlertBot.py
> Check new carrier image size before accepting

- MissionAlertBot.py
> Notify CCO on m.done, reorganise m.done / m.complete to use new shared mission completion functions

- MissionAlertBot.py
> 265- Sanitze the input

- MissionAlertBot.py
Made it an f-string
Fixes #268
> Mission completion to Reddit is not an f-string

- MissionAlertBot.py
> Forgot to commit this earlier

- MissionAlertBot.py
> Deploy fix to main

- README.md
I figured this may help any new devs get contextualized
> Added a really basic README.md

- MissionAlertBot.py
- constants.py
Added option for separate unloading notifictaion
Fixes #300
> 300 - Wine unloading missions should go too separate channel

- MissionAlertBot.py
> Find x by y / m.cc security

- MissionAlertBot.py
> More sensible _cc use for m.cc

- MissionAlertBot.py
> Fix m.complete bug

- MissionAlertBot.py
- add ;stock command; fixes #358 
- add clickable link to channel where possible
> update carrier info embed

- MissionAlertBot.py
> Add author to embed

- MissionAlertBot.py
> update embed description and color on no nomination data

- MissionAlertBot.py
Pin the initial message sent by the bot when it opens the channel
> Pin bot trade message

- MissionAlertBot.py
1. react EDMC OFF in emojis to the trade alert when edmc_off is True #384  
2. fix edmc typos #386 
3. clean up the bot pinned messages on m.done|m.complete  #383 
4. erase the system notification message that a message was pinned in all public guild channels #387 
Demo: https://imgur.com/4gh8F8U
> Edmc pin work

- MissionAlertBot.py
> bot spam embed

- MissionAlertBot.py
- requirements.txt
1. InvalidArgument is no longer a valid exception. It was replaced with the possibility to raise a ValueError or TypeError
2. Move away from discord_slash and use discord.py's built in CommandTree for slash commands.
3. Related to 2 move all `ctx` references to `interaction` with appropriate updates for slash commands
4. move asyncpraw initialization into an async function. Discord.py was failing to run the subreddit posts due to `Timeout context manager should be used inside a task`
5. on the set_permissions() move the permission definition into a function to save a bit of code duplication
6. Related to 4, set_permissions() now expects a Member class and not a User class. Create a function to return the current Guild instance so we can run fetch_member()
I tested every command and slash …
> v2.1.0 updates - The Great Bandaid

- MissionAlertBot.py
> Remove stock command notice in footer for legacy missions channel embed

- MissionAlertBot.py
> Deploy temporary fix 

- MissionAlertBot.py
May or may not solve #441 
If it does, should probably add to all channel moves
> Add check for moving CC to archive category, retry with delay

- MissionAlertBot.py
- constants.py
- version.py
> Add version number, print to dev channel on connect

- MissionAlertBot.py
- version.py
> Fix CC archive bug

- MissionAlertBot.py
> Dev to main

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/botcommands/DatabaseInteraction.py
- ptn/missionalertbot/botcommands/GeneralCommands.py
- ptn/missionalertbot/classes/Views.py
- ptn/missionalertbot/modules/MissionCleaner.py
- ptn/missionalertbot/modules/MissionGenerator.py
- ptn/missionalertbot/modules/helpers.py
> Channel lock improvements

- ptn/missionalertbot/botcommands/GeneralCommands.py
- ptn/missionalertbot/database/database.py
- ptn/missionalertbot/modules/MissionCleaner.py
> Re-implement orphaned trade channel removal on startup

- CHANGELOG.md
- ptn/missionalertbot/botcommands/CCOCommands.py
- ptn/missionalertbot/modules/MissionEditor.py
- ptn/missionalertbot/modules/MissionGenerator.py
> Add capability to edit misison type and message, increase timeouts on mission send/edit views

- CHANGELOG.md
- ptn/missionalertbot/botcommands/GeneralCommands.py
- ptn/missionalertbot/classes/Views.py
- ptn/missionalertbot/modules/ImageHandling.py
- ptn/missionalertbot/modules/MissionCleaner.py
- ptn/missionalertbot/modules/MissionEditor.py
- ptn/missionalertbot/modules/MissionGenerator.py
- ptn/missionalertbot/modules/helpers.py
Fixed #523
Fixed #520
Fixed #524
> various fixes

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/botcommands/CCOCommands.py
- ptn/missionalertbot/botcommands/CTeamCommands.py
- ptn/missionalertbot/botcommands/GeneralCommands.py
- ptn/missionalertbot/classes/Views.py
- ptn/missionalertbot/constants.py
- ptn/missionalertbot/modules/Embeds.py
- ptn/missionalertbot/modules/helpers.py
Fixes #473
Fixes #475
Fixes #474
> Grant role context menu commands

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/botcommands/DatabaseInteraction.py
> ;add_FC code on /carrier_add

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/botcommands/CCOCommands.py
- ptn/missionalertbot/botcommands/CTeamCommands.py
- ptn/missionalertbot/botcommands/DatabaseInteraction.py
- ptn/missionalertbot/botcommands/GeneralCommands.py
- ptn/missionalertbot/classes/Views.py
- ptn/missionalertbot/database/database.py
- ptn/missionalertbot/modules/Embeds.py
- ptn/missionalertbot/modules/ErrorHandler.py
- ptn/missionalertbot/modules/ImageHandling.py
- ptn/missionalertbot/modules/MissionCleaner.py
- ptn/missionalertbot/modules/MissionEditor.py
- ptn/missionalertbot/modules/MissionGenerator.py
- ptn/missionalertbot/modules/helpers.py
Fixes #548 
Fixes #550
Contributes to #549
> Error handling changes

- CHANGELOG.md
- ptn/missionalertbot/modules/MissionGenerator.py
> Fix wine load pings

- ptn/missionalertbot/botcommands/GeneralCommands.py
- ptn/missionalertbot/modules/BackgroundTasks.py
Should probably fix [#580](https://github.com/PilotsTradeNetwork/MissionAlertBot/issues/580)
> Check if background tasks are running before attempting to start them

- ptn/missionalertbot/application.py
- ptn/missionalertbot/botcommands/DatabaseInteraction.py
- ptn/missionalertbot/classes/Commodity.py
- ptn/missionalertbot/database/Commodities.py
- ptn/missionalertbot/database/database.py
Resolves #50 
- Allows users to have a functional fresh install of the bot without creating and populating the commodities table themselves
- Allows for additions to commodity table when needed via adding to Commodities.py
> Logic to create the commodities table from scratch

- CHANGELOG.md
- ptn/missionalertbot/constants.py
- ptn/missionalertbot/modules/ErrorHandler.py
- ptn/missionalertbot/modules/MissionGenerator.py
- ptn/missionalertbot/modules/TextGen.py
- setup.py
> Workaround for PRAW websocket error

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/classes/Views.py
Removed embed footer - no longer needed
Resolves #632
> Fix for 632

- CHANGELOG.md
- ptn/missionalertbot/modules/MissionEditor.py
- ptn/missionalertbot/modules/MissionGenerator.py
> Fix for 635

- CHANGELOG.md
- ptn/missionalertbot/classes/Views.py
- ptn/missionalertbot/constants.py
> Change discord invite link

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/botcommands/DatabaseInteraction.py
- ptn/missionalertbot/classes/Views.py
- ptn/missionalertbot/modules/Embeds.py
> Add carrier purge command

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/application.py
- ptn/missionalertbot/botcommands/CCOCommands.py
- ptn/missionalertbot/botcommands/DatabaseInteraction.py
- ptn/missionalertbot/botcommands/GeneralCommands.py
- ptn/missionalertbot/botcommands/StockTracker.py
- ptn/missionalertbot/classes/CarrierData.py
- ptn/missionalertbot/classes/Views.py
- ptn/missionalertbot/classes/WMMData.py
- ptn/missionalertbot/constants.py
- ptn/missionalertbot/database/database.py
- ptn/missionalertbot/modules/BackgroundTasks.py
- ptn/missionalertbot/modules/Embeds.py
- ptn/missionalertbot/modules/MissionEditor.py
- ptn/missionalertbot/modules/MissionGenerator.py
- ptn/missionalertbot/modules/StockHelpers.py
- ptn/missionalertbot/modules/TextGen.py
- ptn/missionalertbot/modules/helpers.py
- setup.py
Merge functionality from EDStockTracker
> Stock tracker merge

- ptn/missionalertbot/constants.py
- ptn/missionalertbot/modules/BackgroundTasks.py
Use (System, Station, Commodity) as sorting key, so the list will be easier to read.
Also minor refactor to simplify flows and avoid code duplication
> Sort WMM stock messages

- README.md
Sihmm's info was useful to me, might as well include it for future contributors :)
> update README with testing instructions

- CHANGELOG.md
- ptn/missionalertbot/_metadata.py
- ptn/missionalertbot/modules/BackgroundTasks.py
lamo, always one line of code breaking the whole thing fr fr
> Fix for grouping on Inara carriers
